### ISSUE TITLE
Error with user feedback for python 2.6 environments

### ISSUE THREAD

**Issue by etiology** [Raghavan-Lab/SynchronizePairs#4]
There needs to be feedback to users who are attempting to run this in python 2.6 environments.

**Comment by Cabalist** [comment]
Put this at the top of your app entry point:

```python
if sys.hexversion < 0x020703F0:
    print('The system requires at least Python 2.7.3 to run. Please update your Python interpreter.\n')
    sys.exit(1)
```

More info here:
https://docs.python.org/2/library/sys.html#sys.hexversion

It looks more complicated than it is.  You should be able to pick out 2.7.3 from 02 07 03 F0
